#!/bin/bash

set -e
. "$LEDGER_WORKDIR/common"

# Description of the command usage
cli_help_balance() {
    echo "
        Command: balance
        Usage: 
        bal -f <file>
    "
    exit 1
}

# If there was no parameter, print the help
[ ! -n "$1" ] && cli_help_balance

export LEDGER_FILE=$1

cli_log "Balance BEGIN"
cli_log "You sent $1"
cli_log "Balance END"
